# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'artseeapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for artseeapp

  rn_path = '../node_modules/react-native'
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
      'Core'
    ]

  
  pod 'RNDynamicCropper', :path =>  '../node_modules/react-native-dynamic-cropper'
end
# I have problems with UUID error messages running rampant on my dev machine, so this.
install! 'cocoapods',
         :deterministic_uuids => false
# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
